name: Echo Longest Test Run
description: Finds and prints the longest test run

runs:
  using: composite
  steps:
    - name: Echo Longest Test Run
      shell: bash
      run: find . -name TEST-*.xml -exec grep -h testcase {} \; | awk -F '"' '{printf("%s#%s() - %.3f s\n", $4, $2, $6); }' | sort -n -k 3 | tail -20
