pull_request_rules: 
  - name: automatic merge with strict
    conditions:
      - author=alfresco-build-user
      - status-success=CI / build (pull_request)
      - label!=do-not-merge
    actions:
      merge:
        method: merge
        strict: true
  - name: automatic merge when CI passes and 1 approving reviews and label ready-to-merge
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - status-success=CI / build (pull_request)
      - status-success=license/cla
      - label!=do-not-merge
    actions:
      merge:
        method: squash
        strict: true
