github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-dependencies
      branch: develop
      useSinglePullRequest: true
    - name: activiti
      branch: develop
      useSinglePullRequest: true
