update ACT_GE_PROPERTY set VALUE_ = '5.18.0.0' where NAME_ = 'schema.version';

alter table
   ACT_GE_PROPERTY
modify (
    NAME_ VARCHAR2(64),
    VALUE_ VARCHAR2(300)
);

alter table
    ACT_GE_BYTEARRAY
modify (
    ID_ VARCHAR2(64),
    NAME_ VARCHAR2(255),
    DEPLOYMENT_ID_ VARCHAR2(64)
);

alter table ACT_RE_DEPLOYMENT
modify (
    ID_ VARCHAR2(64),
    NAME_ VARCHAR2(255),
    CATEGORY_ VARCHAR2(255),
    TENANT_ID_ VARCHAR2(255) DEFAULT ''
);

alter table ACT_RE_MODEL
modify (
    ID_ VARCHAR2(64) not null,
    NAME_ VARCHAR2(255),
    KEY_ VARCHAR2(255),
    CATEGORY_ VARCHAR2(255),
    META_INFO_ VARCHAR2(2000),
    DEPLOYMENT_ID_ VARCHAR2(64),
    EDITOR_SOURCE_VALUE_ID_ VARCHAR2(64),
    EDITOR_SOURCE_EXTRA_VALUE_ID_ VARCHAR2(64),
    TENANT_ID_ VARCHAR2(255) DEFAULT ''
);

alter table ACT_RU_EXECUTION
modify (
    ID_ VARCHAR2(64),
    PROC_INST_ID_ VARCHAR2(64),
    BUSINESS_KEY_ VARCHAR2(255),
    PARENT_ID_ VARCHAR2(64),
    PROC_DEF_ID_ VARCHAR2(64),
    SUPER_EXEC_ VARCHAR2(64),
    ACT_ID_ VARCHAR2(255),
    NAME_ VARCHAR2(255)
);

alter table ACT_RU_JOB
modify (
    ID_ VARCHAR2(64) NOT NULL,
    TYPE_ VARCHAR2(255) NOT NULL,
    LOCK_OWNER_ VARCHAR2(255),
    EXECUTION_ID_ VARCHAR2(64),
    PROCESS_INSTANCE_ID_ VARCHAR2(64),
    PROC_DEF_ID_ VARCHAR2(64),
    EXCEPTION_STACK_ID_ VARCHAR2(64),
    EXCEPTION_MSG_ VARCHAR2(2000),
    REPEAT_ VARCHAR2(255),
    HANDLER_TYPE_ VARCHAR2(255),
    HANDLER_CFG_ VARCHAR2(2000),
    TENANT_ID_ VARCHAR2(255) DEFAULT ''
);

alter table ACT_RE_PROCDEF
modify (
    ID_ VARCHAR2(64) NOT NULL,
    CATEGORY_ VARCHAR2(255),
    NAME_ VARCHAR2(255),
    KEY_ VARCHAR2(255) NOT NULL,
    DEPLOYMENT_ID_ VARCHAR2(64),
    RESOURCE_NAME_ VARCHAR2(2000),
    DGRM_RESOURCE_NAME_ varchar(4000),
    DESCRIPTION_ VARCHAR2(2000),
    TENANT_ID_ VARCHAR2(255) DEFAULT ''
);

alter table ACT_RU_TASK
modify (
    ID_ VARCHAR2(64),
    EXECUTION_ID_ VARCHAR2(64),
    PROC_INST_ID_ VARCHAR2(64),
    PROC_DEF_ID_ VARCHAR2(64),
    NAME_ VARCHAR2(255),
    PARENT_TASK_ID_ VARCHAR2(64),
    DESCRIPTION_ VARCHAR2(2000),
    TASK_DEF_KEY_ VARCHAR2(255),
    OWNER_ VARCHAR2(255),
    ASSIGNEE_ VARCHAR2(255),
    DELEGATION_ VARCHAR2(64),
    CATEGORY_ VARCHAR2(255),
    TENANT_ID_ VARCHAR2(255) DEFAULT '',
    FORM_KEY_ VARCHAR2(255)
);

alter table ACT_RU_IDENTITYLINK
modify (
    ID_ VARCHAR2(64),
    GROUP_ID_ VARCHAR2(255),
    TYPE_ VARCHAR2(255),
    USER_ID_ VARCHAR2(255),
    TASK_ID_ VARCHAR2(64),
    PROC_INST_ID_ VARCHAR2(64),
    PROC_DEF_ID_ VARCHAR2(64)
);

alter table ACT_RU_VARIABLE
modify (
    ID_ VARCHAR2(64) not null,
    TYPE_ VARCHAR2(255) not null,
    NAME_ VARCHAR2(255) not null,
    EXECUTION_ID_ VARCHAR2(64),
    PROC_INST_ID_ VARCHAR2(64),
    TASK_ID_ VARCHAR2(64),
    BYTEARRAY_ID_ VARCHAR2(64),
    TEXT_ VARCHAR2(2000),
    TEXT2_ VARCHAR2(2000),
);

alter table ACT_RU_EVENT_SUBSCR
modify (
    ID_ VARCHAR2(64) not null,
    EVENT_TYPE_ VARCHAR2(255) not null,
    EVENT_NAME_ VARCHAR2(255),
    EXECUTION_ID_ VARCHAR2(64),
    PROC_INST_ID_ VARCHAR2(64),
    ACTIVITY_ID_ VARCHAR2(64),
    CONFIGURATION_ VARCHAR2(255),
    PROC_DEF_ID_ VARCHAR2(64),
    TENANT_ID_ VARCHAR2(255) DEFAULT ''
);

alter table ACT_EVT_LOG
modify (
    TYPE_ VARCHAR2(64),
    PROC_DEF_ID_ VARCHAR2(64),
    PROC_INST_ID_ VARCHAR2(64),
    EXECUTION_ID_ VARCHAR2(64),
    TASK_ID_ VARCHAR2(64),
    USER_ID_ VARCHAR2(255),
    LOCK_OWNER_ VARCHAR2(255)
);
