create table ACT_CY_CONN_CONFIG (
	ID_ NVARCHAR2(255) NOT NULL,
	PLUGIN_ID_ NVARCHAR2(255) NOT NULL,
	INSTANCE_NAME_ NVARCHAR2(255) NOT NULL, 
	INSTANCE_ID_ NVARCHAR2(255) NOT NULL,  
	USER_ NVARCHAR2(255),
	GROUP_ NVARCHAR2(255),
	VALUES_ clob,	
	primary key (ID_)
);

drop table ACT_CY_CONFIG;

create table ACT_CY_CONFIG (
	ID_ NVARCHAR2(255) NOT NULL,
	GROUP_ NVARCHAR2(255) NOT NULL,
	KEY_ NVARCHAR2(255) NOT NULL,
	VALUE_ clob,
	primary key (ID_)
);

