package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActGeBytearray generated by hbm2java
 */
@Entity
@Table(name="act_ge_bytearray")
public class ActGeBytearray  implements java.io.Serializable {


     private String id;
     private ActReDeployment actReDeployment;
     private Integer rev;
     private String name;
     private byte[] bytes;
     private Boolean generated;
     private Set<ActReModel> actReModelsForEditorSourceValueId = new HashSet<ActReModel>(0);
     private Set<ActRuJob> actRuJobs = new HashSet<ActRuJob>(0);
     private Set<ActProcdefInfo> actProcdefInfos = new HashSet<ActProcdefInfo>(0);
     private Set<ActReModel> actReModelsForEditorSourceExtraValueId = new HashSet<ActReModel>(0);
     private Set<ActRuVariable> actRuVariables = new HashSet<ActRuVariable>(0);

    public ActGeBytearray() {
    }

	
    public ActGeBytearray(String id) {
        this.id = id;
    }
    public ActGeBytearray(String id, ActReDeployment actReDeployment, Integer rev, String name, byte[] bytes, Boolean generated, Set<ActReModel> actReModelsForEditorSourceValueId, Set<ActRuJob> actRuJobs, Set<ActProcdefInfo> actProcdefInfos, Set<ActReModel> actReModelsForEditorSourceExtraValueId, Set<ActRuVariable> actRuVariables) {
       this.id = id;
       this.actReDeployment = actReDeployment;
       this.rev = rev;
       this.name = name;
       this.bytes = bytes;
       this.generated = generated;
       this.actReModelsForEditorSourceValueId = actReModelsForEditorSourceValueId;
       this.actRuJobs = actRuJobs;
       this.actProcdefInfos = actProcdefInfos;
       this.actReModelsForEditorSourceExtraValueId = actReModelsForEditorSourceExtraValueId;
       this.actRuVariables = actRuVariables;
    }
   
     @Id 
    
    @Column(name="id_", unique=true, nullable=false, length=64)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deployment_id_")
    public ActReDeployment getActReDeployment() {
        return this.actReDeployment;
    }
    
    public void setActReDeployment(ActReDeployment actReDeployment) {
        this.actReDeployment = actReDeployment;
    }
    
    @Column(name="rev_")
    public Integer getRev() {
        return this.rev;
    }
    
    public void setRev(Integer rev) {
        this.rev = rev;
    }
    
    @Column(name="name_")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="bytes_")
    public byte[] getBytes() {
        return this.bytes;
    }
    
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }
    
    @Column(name="generated_")
    public Boolean getGenerated() {
        return this.generated;
    }
    
    public void setGenerated(Boolean generated) {
        this.generated = generated;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actGeBytearrayByEditorSourceValueId")
    public Set<ActReModel> getActReModelsForEditorSourceValueId() {
        return this.actReModelsForEditorSourceValueId;
    }
    
    public void setActReModelsForEditorSourceValueId(Set<ActReModel> actReModelsForEditorSourceValueId) {
        this.actReModelsForEditorSourceValueId = actReModelsForEditorSourceValueId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actGeBytearray")
    public Set<ActRuJob> getActRuJobs() {
        return this.actRuJobs;
    }
    
    public void setActRuJobs(Set<ActRuJob> actRuJobs) {
        this.actRuJobs = actRuJobs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actGeBytearray")
    public Set<ActProcdefInfo> getActProcdefInfos() {
        return this.actProcdefInfos;
    }
    
    public void setActProcdefInfos(Set<ActProcdefInfo> actProcdefInfos) {
        this.actProcdefInfos = actProcdefInfos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actGeBytearrayByEditorSourceExtraValueId")
    public Set<ActReModel> getActReModelsForEditorSourceExtraValueId() {
        return this.actReModelsForEditorSourceExtraValueId;
    }
    
    public void setActReModelsForEditorSourceExtraValueId(Set<ActReModel> actReModelsForEditorSourceExtraValueId) {
        this.actReModelsForEditorSourceExtraValueId = actReModelsForEditorSourceExtraValueId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actGeBytearray")
    public Set<ActRuVariable> getActRuVariables() {
        return this.actRuVariables;
    }
    
    public void setActRuVariables(Set<ActRuVariable> actRuVariables) {
        this.actRuVariables = actRuVariables;
    }




}


