package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ActHiProcinst generated by hbm2java
 */
@Entity
@Table(name="act_hi_procinst"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="proc_inst_id_") 
)
public class ActHiProcinst  implements java.io.Serializable {


     private String id;
     private String procInstId;
     private String businessKey;
     private String procDefId;
     private Date startTime;
     private Date endTime;
     private Long duration;
     private String startUserId;
     private String startActId;
     private String endActId;
     private String superProcessInstanceId;
     private String deleteReason;
     private String tenantId;
     private String name;

    public ActHiProcinst() {
    }

	
    public ActHiProcinst(String id, String procInstId, String procDefId, Date startTime) {
        this.id = id;
        this.procInstId = procInstId;
        this.procDefId = procDefId;
        this.startTime = startTime;
    }
    public ActHiProcinst(String id, String procInstId, String businessKey, String procDefId, Date startTime, Date endTime, Long duration, String startUserId, String startActId, String endActId, String superProcessInstanceId, String deleteReason, String tenantId, String name) {
       this.id = id;
       this.procInstId = procInstId;
       this.businessKey = businessKey;
       this.procDefId = procDefId;
       this.startTime = startTime;
       this.endTime = endTime;
       this.duration = duration;
       this.startUserId = startUserId;
       this.startActId = startActId;
       this.endActId = endActId;
       this.superProcessInstanceId = superProcessInstanceId;
       this.deleteReason = deleteReason;
       this.tenantId = tenantId;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="id_", unique=true, nullable=false, length=64)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="proc_inst_id_", unique=true, nullable=false, length=64)
    public String getProcInstId() {
        return this.procInstId;
    }
    
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }
    
    @Column(name="business_key_")
    public String getBusinessKey() {
        return this.businessKey;
    }
    
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }
    
    @Column(name="proc_def_id_", nullable=false, length=64)
    public String getProcDefId() {
        return this.procDefId;
    }
    
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_time_", nullable=false, length=29)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_time_", length=29)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="duration_")
    public Long getDuration() {
        return this.duration;
    }
    
    public void setDuration(Long duration) {
        this.duration = duration;
    }
    
    @Column(name="start_user_id_")
    public String getStartUserId() {
        return this.startUserId;
    }
    
    public void setStartUserId(String startUserId) {
        this.startUserId = startUserId;
    }
    
    @Column(name="start_act_id_")
    public String getStartActId() {
        return this.startActId;
    }
    
    public void setStartActId(String startActId) {
        this.startActId = startActId;
    }
    
    @Column(name="end_act_id_")
    public String getEndActId() {
        return this.endActId;
    }
    
    public void setEndActId(String endActId) {
        this.endActId = endActId;
    }
    
    @Column(name="super_process_instance_id_", length=64)
    public String getSuperProcessInstanceId() {
        return this.superProcessInstanceId;
    }
    
    public void setSuperProcessInstanceId(String superProcessInstanceId) {
        this.superProcessInstanceId = superProcessInstanceId;
    }
    
    @Column(name="delete_reason_", length=4000)
    public String getDeleteReason() {
        return this.deleteReason;
    }
    
    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason;
    }
    
    @Column(name="tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
    
    @Column(name="name_")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


