package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * ActProcdefInfo generated by hbm2java
 */
@Entity
@Table(name = "act_procdef_info",
        uniqueConstraints = @UniqueConstraint(columnNames = "proc_def_id_")
)
public class ActProcdefInfo implements java.io.Serializable {

    private String id;
    private ActReProcdef actReProcdef;
    private ActGeBytearray actGeBytearray;
    private Integer rev;

    public ActProcdefInfo() {
    }

    public ActProcdefInfo(String id, ActReProcdef actReProcdef) {
        this.id = id;
        this.actReProcdef = actReProcdef;
    }

    public ActProcdefInfo(String id, ActReProcdef actReProcdef, ActGeBytearray actGeBytearray, Integer rev) {
        this.id = id;
        this.actReProcdef = actReProcdef;
        this.actGeBytearray = actGeBytearray;
        this.rev = rev;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_def_id_", unique = true, nullable = false)
    public ActReProcdef getActReProcdef() {
        return this.actReProcdef;
    }

    public void setActReProcdef(ActReProcdef actReProcdef) {
        this.actReProcdef = actReProcdef;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "info_json_id_")
    public ActGeBytearray getActGeBytearray() {
        return this.actGeBytearray;
    }

    public void setActGeBytearray(ActGeBytearray actGeBytearray) {
        this.actGeBytearray = actGeBytearray;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }


}


