package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActReDeployment generated by hbm2java
 */
@Entity
@Table(name="act_re_deployment"
    ,schema="public"
)
public class ActReDeployment  implements java.io.Serializable {


     private String id;
     private String name;
     private String category;
     private String tenantId;
     private Date deployTime;
     private Set<ActReModel> actReModels = new HashSet<ActReModel>(0);
     private Set<ActGeBytearray> actGeBytearraies = new HashSet<ActGeBytearray>(0);

    public ActReDeployment() {
    }

	
    public ActReDeployment(String id) {
        this.id = id;
    }
    public ActReDeployment(String id, String name, String category, String tenantId, Date deployTime, Set<ActReModel> actReModels, Set<ActGeBytearray> actGeBytearraies) {
       this.id = id;
       this.name = name;
       this.category = category;
       this.tenantId = tenantId;
       this.deployTime = deployTime;
       this.actReModels = actReModels;
       this.actGeBytearraies = actGeBytearraies;
    }
   
     @Id 
    
    @Column(name="id_", unique=true, nullable=false, length=64)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name_")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="category_")
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    
    @Column(name="tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deploy_time_", length=29)
    public Date getDeployTime() {
        return this.deployTime;
    }
    
    public void setDeployTime(Date deployTime) {
        this.deployTime = deployTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actReDeployment")
    public Set<ActReModel> getActReModels() {
        return this.actReModels;
    }
    
    public void setActReModels(Set<ActReModel> actReModels) {
        this.actReModels = actReModels;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actReDeployment")
    public Set<ActGeBytearray> getActGeBytearraies() {
        return this.actGeBytearraies;
    }
    
    public void setActGeBytearraies(Set<ActGeBytearray> actGeBytearraies) {
        this.actGeBytearraies = actGeBytearraies;
    }




}


