package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * ActRuIdentitylink generated by hbm2java
 */
@Entity
@Table(name = "act_ru_identitylink"
        , schema = "public"
)
public class ActRuIdentitylink implements java.io.Serializable {


    private String id;
    private ActReProcdef actReProcdef;
    private ActRuTask actRuTask;
    private ActRuExecution actRuExecution;
    private Integer rev;
    private String groupId;
    private String type;
    private String userId;

    public ActRuIdentitylink() {
    }


    public ActRuIdentitylink(String id) {
        this.id = id;
    }

    public ActRuIdentitylink(String id, ActReProcdef actReProcdef, ActRuTask actRuTask, ActRuExecution actRuExecution, Integer rev, String groupId, String type, String userId) {
        this.id = id;
        this.actReProcdef = actReProcdef;
        this.actRuTask = actRuTask;
        this.actRuExecution = actRuExecution;
        this.rev = rev;
        this.groupId = groupId;
        this.type = type;
        this.userId = userId;
    }

    @Id

    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_def_id_")
    public ActReProcdef getActReProcdef() {
        return this.actReProcdef;
    }

    public void setActReProcdef(ActReProcdef actReProcdef) {
        this.actReProcdef = actReProcdef;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id_")
    public ActRuTask getActRuTask() {
        return this.actRuTask;
    }

    public void setActRuTask(ActRuTask actRuTask) {
        this.actRuTask = actRuTask;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_inst_id_")
    public ActRuExecution getActRuExecution() {
        return this.actRuExecution;
    }

    public void setActRuExecution(ActRuExecution actRuExecution) {
        this.actRuExecution = actRuExecution;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "group_id_")
    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @Column(name = "type_")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "user_id_")
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }


}


