package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * ActRuVariable generated by hbm2java
 */
@Entity
@Table(name = "act_ru_variable"
        , schema = "public"
)
public class ActRuVariable implements java.io.Serializable {


    private String id;
    private ActRuExecution actRuExecutionByExecutionId;
    private ActGeBytearray actGeBytearray;
    private ActRuExecution actRuExecutionByProcInstId;
    private Integer rev;
    private String type;
    private String name;
    private String taskId;
    private Double double_;
    private Long long_;
    private String text;
    private String text2;

    public ActRuVariable() {
    }


    public ActRuVariable(String id, String type, String name) {
        this.id = id;
        this.type = type;
        this.name = name;
    }

    public ActRuVariable(String id, ActRuExecution actRuExecutionByExecutionId, ActGeBytearray actGeBytearray, ActRuExecution actRuExecutionByProcInstId, Integer rev, String type, String name, String taskId, Double double_, Long long_, String text, String text2) {
        this.id = id;
        this.actRuExecutionByExecutionId = actRuExecutionByExecutionId;
        this.actGeBytearray = actGeBytearray;
        this.actRuExecutionByProcInstId = actRuExecutionByProcInstId;
        this.rev = rev;
        this.type = type;
        this.name = name;
        this.taskId = taskId;
        this.double_ = double_;
        this.long_ = long_;
        this.text = text;
        this.text2 = text2;
    }

    @Id

    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "execution_id_")
    public ActRuExecution getActRuExecutionByExecutionId() {
        return this.actRuExecutionByExecutionId;
    }

    public void setActRuExecutionByExecutionId(ActRuExecution actRuExecutionByExecutionId) {
        this.actRuExecutionByExecutionId = actRuExecutionByExecutionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bytearray_id_")
    public ActGeBytearray getActGeBytearray() {
        return this.actGeBytearray;
    }

    public void setActGeBytearray(ActGeBytearray actGeBytearray) {
        this.actGeBytearray = actGeBytearray;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_inst_id_")
    public ActRuExecution getActRuExecutionByProcInstId() {
        return this.actRuExecutionByProcInstId;
    }

    public void setActRuExecutionByProcInstId(ActRuExecution actRuExecutionByProcInstId) {
        this.actRuExecutionByProcInstId = actRuExecutionByProcInstId;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "type_", nullable = false)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "name_", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "task_id_", length = 64)
    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Column(name = "double_", precision = 17, scale = 17)
    public Double getDouble_() {
        return this.double_;
    }

    public void setDouble_(Double double_) {
        this.double_ = double_;
    }

    @Column(name = "long_")
    public Long getLong_() {
        return this.long_;
    }

    public void setLong_(Long long_) {
        this.long_ = long_;
    }

    @Column(name = "text_", length = 4000)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "text2_", length = 4000)
    public String getText2() {
        return this.text2;
    }

    public void setText2(String text2) {
        this.text2 = text2;
    }


}


