package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ByteArray generated by hbm2java
 */
@Entity
@Table(name = "act_ge_bytearray")
public class ByteArray implements java.io.Serializable {


    private String id;
    private Deployment deployment;
    private Integer rev;
    private String name;
    private byte[] bytes;
    private Boolean generated;
    private Set<Model> modelsForEditorSourceValueId = new HashSet<Model>(0);
    private Set<Job> jobs = new HashSet<Job>(0);
    private Set<ProcessDefinitionInfo> processDefinitionInfos = new HashSet<ProcessDefinitionInfo>(0);
    private Set<Model> modelsForEditorSourceExtraValueId = new HashSet<Model>(0);
    private Set<VariableInstance> variableInstances = new HashSet<VariableInstance>(0);

    public ByteArray() {
    }


    public ByteArray(String id) {
        this.id = id;
    }

    public ByteArray(String id, Deployment deployment, Integer rev, String name, byte[] bytes, Boolean generated, Set<Model> modelsForEditorSourceValueId, Set<Job> jobs, Set<ProcessDefinitionInfo> processDefinitionInfos, Set<Model> modelsForEditorSourceExtraValueId, Set<VariableInstance> variableInstances) {
        this.id = id;
        this.deployment = deployment;
        this.rev = rev;
        this.name = name;
        this.bytes = bytes;
        this.generated = generated;
        this.modelsForEditorSourceValueId = modelsForEditorSourceValueId;
        this.jobs = jobs;
        this.processDefinitionInfos = processDefinitionInfos;
        this.modelsForEditorSourceExtraValueId = modelsForEditorSourceExtraValueId;
        this.variableInstances = variableInstances;
    }

    @Id

    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deployment_id_")
    public Deployment getDeployment() {
        return this.deployment;
    }

    public void setDeployment(Deployment deployment) {
        this.deployment = deployment;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "name_")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "bytes_")
    public byte[] getBytes() {
        return this.bytes;
    }

    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }

    @Column(name = "generated_")
    public Boolean getGenerated() {
        return this.generated;
    }

    public void setGenerated(Boolean generated) {
        this.generated = generated;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actGeBytearrayByEditorSourceValueId")
    public Set<Model> getModelsForEditorSourceValueId() {
        return this.modelsForEditorSourceValueId;
    }

    public void setModelsForEditorSourceValueId(Set<Model> modelsForEditorSourceValueId) {
        this.modelsForEditorSourceValueId = modelsForEditorSourceValueId;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
    public Set<Job> getJobs() {
        return this.jobs;
    }

    public void setJobs(Set<Job> jobs) {
        this.jobs = jobs;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
    public Set<ProcessDefinitionInfo> getProcessDefinitionInfos() {
        return this.processDefinitionInfos;
    }

    public void setProcessDefinitionInfos(Set<ProcessDefinitionInfo> processDefinitionInfos) {
        this.processDefinitionInfos = processDefinitionInfos;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actGeBytearrayByEditorSourceExtraValueId")
    public Set<Model> getModelsForEditorSourceExtraValueId() {
        return this.modelsForEditorSourceExtraValueId;
    }

    public void setModelsForEditorSourceExtraValueId(Set<Model> modelsForEditorSourceExtraValueId) {
        this.modelsForEditorSourceExtraValueId = modelsForEditorSourceExtraValueId;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
    public Set<VariableInstance> getVariableInstances() {
        return this.variableInstances;
    }

    public void setVariableInstances(Set<VariableInstance> variableInstances) {
        this.variableInstances = variableInstances;
    }


}


