package org.activiti.springdatajpa.pojo;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessDefinition generated by hbm2java
 */
@Entity
@Table(name = "act_re_procdef"
        , schema = "public"
        , uniqueConstraints = @UniqueConstraint(columnNames = {"key_", "version_", "tenant_id_"})
)
public class ProcessDefinition implements java.io.Serializable {

    private String id;
    private Integer rev;
    private String category;
    private String name;
    private String key;
    private int version;
    private String deploymentId;
    private String resourceName;
    private String dgrmResourceName;
    private String description;
    private Boolean hasStartFormKey;
    private Boolean hasGraphicalNotation;
    private Integer suspensionState;
    private String tenantId;
    private Set<Execution> executions = new HashSet<Execution>(0);
    private Set<ProcessDefinitionInfo> processDefinitionInfos = new HashSet<ProcessDefinitionInfo>(0);
    private Set<Task> tasks = new HashSet<Task>(0);
    private Set<IdentityLink> identityLinks = new HashSet<IdentityLink>(0);

    public ProcessDefinition() {
    }

    public ProcessDefinition(String id, String key, int version) {
        this.id = id;
        this.key = key;
        this.version = version;
    }

    public ProcessDefinition(String id, Integer rev, String category, String name, String key, int version, String deploymentId, String resourceName, String dgrmResourceName, String description, Boolean hasStartFormKey, Boolean hasGraphicalNotation, Integer suspensionState, String tenantId, Set<Execution> executions, Set<ProcessDefinitionInfo> processDefinitionInfos, Set<Task> tasks, Set<IdentityLink> identityLinks) {
        this.id = id;
        this.rev = rev;
        this.category = category;
        this.name = name;
        this.key = key;
        this.version = version;
        this.deploymentId = deploymentId;
        this.resourceName = resourceName;
        this.dgrmResourceName = dgrmResourceName;
        this.description = description;
        this.hasStartFormKey = hasStartFormKey;
        this.hasGraphicalNotation = hasGraphicalNotation;
        this.suspensionState = suspensionState;
        this.tenantId = tenantId;
        this.executions = executions;
        this.processDefinitionInfos = processDefinitionInfos;
        this.tasks = tasks;
        this.identityLinks = identityLinks;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "category_")
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name = "name_")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "key_", nullable = false)
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @Column(name = "version_", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "deployment_id_", length = 64)
    public String getDeploymentId() {
        return this.deploymentId;
    }

    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId;
    }

    @Column(name = "resource_name_", length = 4000)
    public String getResourceName() {
        return this.resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    @Column(name = "dgrm_resource_name_", length = 4000)
    public String getDgrmResourceName() {
        return this.dgrmResourceName;
    }

    public void setDgrmResourceName(String dgrmResourceName) {
        this.dgrmResourceName = dgrmResourceName;
    }

    @Column(name = "description_", length = 4000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "has_start_form_key_")
    public Boolean getHasStartFormKey() {
        return this.hasStartFormKey;
    }

    public void setHasStartFormKey(Boolean hasStartFormKey) {
        this.hasStartFormKey = hasStartFormKey;
    }

    @Column(name = "has_graphical_notation_")
    public Boolean getHasGraphicalNotation() {
        return this.hasGraphicalNotation;
    }

    public void setHasGraphicalNotation(Boolean hasGraphicalNotation) {
        this.hasGraphicalNotation = hasGraphicalNotation;
    }

    @Column(name = "suspension_state_")
    public Integer getSuspensionState() {
        return this.suspensionState;
    }

    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    @Column(name = "tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actReProcdef")
    public Set<Execution> getExecutions() {
        return this.executions;
    }

    public void setExecutions(Set<Execution> executions) {
        this.executions = executions;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actReProcdef")
    public Set<ProcessDefinitionInfo> getProcessDefinitionInfos() {
        return this.processDefinitionInfos;
    }

    public void setProcessDefinitionInfos(Set<ProcessDefinitionInfo> processDefinitionInfos) {
        this.processDefinitionInfos = processDefinitionInfos;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actReProcdef")
    public Set<Task> getTasks() {
        return this.tasks;
    }

    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actReProcdef")
    public Set<IdentityLink> getIdentityLinks() {
        return this.identityLinks;
    }

    public void setIdentityLinks(Set<IdentityLink> identityLinks) {
        this.identityLinks = identityLinks;
    }
}


