ALTER TABLE ACT_RU_VARIABLE ADD CONTENT_STORE_NAME_ NVARCHAR(64) NULL;
ALTER TABLE ACT_RU_VARIABLE ADD CONTENT_ID_ NVARCHAR(512) NULL;
update ACT_GE_PROPERTY set VALUE_ = '9.1.1' where NAME_ = 'schema.version';
