update ACT_GE_PROPERTY set VALUE_ = '7.11.1' where NAME_ = 'schema.version';

create index ACT_IDX_HI_IDENT_LNK_GROUP on ACT_HI_IDENTITYLINK(GROUP_ID_);

create index ACT_IDX_HI_TASK_INST_START_TIME on ACT_HI_TASKINST(START_TIME_);
create index ACT_IDX_HI_TASK_INST_CLAIM_TIME on ACT_HI_TASKINST(CLAIM_TIME_);
create index ACT_IDX_HI_TASK_INST_END_TIME on ACT_HI_TASKINST(END_TIME_);
create index ACT_IDX_HI_TASK_INST_DUE_DATE on ACT_HI_TASKINST(DUE_DATE_);
