
== Introduction

[[license]]

=== License

Activiti is distributed under link:$$http://www.apache.org/licenses/LICENSE-2.0.html$$[the Apache V2 license].
The Activiti Modeler uses a different license link:$$http://opensource.org/licenses/LGPL-2.1$$[the LGPL 2.1 license].

[[download]]

=== Download

link:$$http://activiti.org/download.html$$[http://activiti.org/download.html]

[[sources]]

=== Sources

The distribution contains most of the sources as jar files. The source code of Activiti can be found on
  link:$$https://github.com/Activiti/Activiti$$[https://github.com/Activiti/Activiti]


[[required.software]]

=== Required software

==== JDK 6+

Activiti runs on a JDK higher than or equal to version 6.  Go to link:$$http://www.oracle.com/technetwork/java/javase/downloads/index.html$$[Oracle Java SE downloads] and click on button "Download JDK".  There are installation instructions on that page as well. To verify that your installation was successful, run +java -version+ on the command line.  That should print the installed version of your JDK.


==== Eclipse Indigo and Juno

Download the eclipse distribution of your choice from link:$$http://www.eclipse.org/downloads/$$[the Eclipse download page]. Unzip the downloaded file and then you should be able to start it with the eclipse file in the directory +eclipse+.
Further in this user guide, there is a section on <<eclipseDesignerInstallation,installing our eclipse designer plugin>>.


[[reporting.problems]]

=== Reporting problems

Every self-respecting developer should have read link:$$http://www.catb.org/~esr/faqs/smart-questions.html$$[How to ask questions the smart way].


After you've done that you can post questions and comments on link:$$http://forums.activiti.org/en/viewforum.php?f=3$$[the Users forum] and create issues in link:$$https://activiti.atlassian.net$$[our JIRA issue tracker].

[NOTE]
====

Even though Activiti is hosted on GitHub, issues should not be reported using GitHub's issue system. If you wish to report an issue, do not create a GitHub issue, but use link:$$https://activiti.atlassian.net$$[our JIRA].

====

[[experimental]]

=== Experimental features

Sections marked with *[EXPERIMENTAL]* should
  not be considered stable.


All classes that have +.impl.+ in the package name are internal implementation classes and cannot be considered stable.  However, if the user guide mentions those classes as configuration values, they are supported and can be considered stable.


[[internal]]

=== Internal implementation classes

In the jar file, all classes in packages that have +.impl.+ (e.g. ++org.activiti.engine.impl.pvm.delegate++) in them are implementation classes and should be considered internal. No stability guarantees are given on classes or interfaces that are in implementation classes.
