[[Tooling]]
== Tooling

[[JMX]]


=== JMX

[[jmxIntroduction]]

==== Introduction


It is possible to connect to Activiti engine using standard Java Management Extensions (JMX) technology in order to get information or to change its behavior. Any standard JMX client can be used for that purpose. Enabling and disabling Job Executor, deploy new process definition files and deleting them are just samples of what could be done using JMX without writing a single line of code.


[[jmxQuickStart]]


==== Quick Start

By default JMX is not enabled. To enable JMX in its default configuration, it is enough to add the activiti-jmx jar file to your classpath, using Maven or by any other means. In case you are using Maven, you can add proper dependency by adding the following lines in your pom.xml:

[source,xml,linenums]
----
<dependency>
  <groupId>org.activiti</groupId>
  <artifactId>activiti-jmx</artifactId>
  <version>latest.version</version>
</dependency>
----

After adding the dependency and building process engine, the JMX connection is ready to be used. Just run jconsole available in a standard JDK distribution. In the list of local processes, you will see the JVM containing Activiti. If for any reason the proper JVM is not listed in "local processes" section, try connecting to it using this URL in "Remote Process" section:


----
service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi/activiti
----

You can find the exact local URL in your log files. After connecting, you can see the standard JVM statistics and MBeans. You can view Activiti specific MBeans by selecting MBeans tab and select "org.activiti.jmx.Mbeans" on the right panel. By selecting any MBean, you can query information or change configuration. This snapshot shows how the jconsole looks like:

Any JMX client not limited to jconsole can be used to access MBeans. Most of data center monitoring tools have some connectors which enables them to connect to JMX MBeans.


==== Attributes and operations


Here is a list available attributes and operations at this moment. This list may extend in future releases based on needs.

[options="header"]
|===============
|MBean|Type|Name|Description
|ProcessDefinitionsMBean|Attribute|processDefinitions|+Id+, +Name+, +Version+, +IsSuspended+ properties of deployed process definitions as a list of list of Strings
||Attribute|deployments|+Id+, +Name+, +TenantId+ properties of current deployments
||method|getProcessDefinitionById(String id)|+Id+, +Name+, +Version+ and +IsSuspended+ properties of the process definition with given id
||method|deleteDeployment(String id)|Deletes deployment with the given +Id+
||method|suspendProcessDefinitionById(String id)|Suspends the process definition with the given +Id+
||method|activatedProcessDefinitionById(String id)|Activates the process definition with the given +Id+
||method|suspendProcessDefinitionByKey(String id)|Suspends the process definition with the given +key+
||method|activatedProcessDefinitionByKey(String id)|Activates the process definition with the given +key+
||method|deployProcessDefinition(String resourceName, String processDefinitionFile)|Deploys the process definition file
|JobExecutorMBean|attribute|isJobExecutorActivated|Returns true if job executor is activated, false otherwise
||method|setJobExecutorActivate(Boolean active)|Activates and Deactivates Job executor based on the given boolean

|===============


==== Configuration

JMX uses default configuration to make it easy to deploy with the most used configuration. However it is easy to change the default configuration. You can do it programmatically or via configuration file. The following code excerpt shows  how this could be done in the configuration file:

[source,xml,linenums]
----
<bean id="processEngineConfiguration" class="...SomeProcessEngineConfigurationClass">
  ...
  <property name="configurators">
    <list>
	  <bean class="org.activiti.management.jmx.JMXConfigurator">

	    <property name="connectorPort" value="1912" />
        <property name="serviceUrlPath" value="/jmxrmi/activiti" />

		...
      </bean>
    </list>
  </property>
</bean>
----

This table shows what parameters you can configure along with their default values:

[options="header"]
|===============
|Name|Default value|Description
|disabled|false|if set, JMX will not be started even in presence of the dependency
|domain|org.activiti.jmx.Mbeans|Domain of MBean
|createConnector|true|if true, creates a connector for the started MbeanServer
|MBeanDomain|DefaultDomain|domain of MBean server
|registryPort|1099|appears in the service URL as registry port
|serviceUrlPath|/jmxrmi/activiti|appears in the service URL
|connectorPort|-1|if greater than zero, will appear in service URL as connector port

|===============



==== JMX Service URL


The JMX service URL has the following format:


----
service:jmx:rmi://<hostName>:<connectorPort>/jndi/rmi://<hostName>:<registryPort>/<serviceUrlPath>
----

+hostName+ will be automatically set to the network name of the machine.
+connectorPort+, +registryPort+ and +serviceUrlPath+ can be configured.


If +connectionPort+ is less than zero, the corresponding part of service URL will be dropped and it will be simplified to:

----
service:jmx:rmi:///jndi/rmi://:<hostname>:<registryPort>/<serviceUrlPath>
----


[[mavenArchetypes]]
=== Maven archetypes


==== Create Test Case
During development, sometimes it is helpful to create a small test case to test an idea or a feature,
before implementing it in the real application.
This helps to isolate the subject under test. JUnit test cases are also the preferred tools for communicating
bug reports and feature requests.
Having a test case attached to a bug report or feature request jira issue, considerably reduces its fixing time.

To facilitate creation of a test case, a maven archetype is available. By use of this archetype, one can rapidly create a standard test case.
The archetype should be already available in the standard repository. If not, you can easily install it in your local maven repository folder by just typing
  *mvn install* in *tooling/archtypes* folder.

The following command creates the unit test project:
[source]

mvn archetype:generate \
-DarchetypeGroupId=org.activiti \
-DarchetypeArtifactId=activiti-archetype-unittest \
-DarchetypeVersion=5.22.0 \
-DgroupId=org.myGroup \
-DartifactId=myArtifact

The effect of each parameter is explained in the following table:

.Unittest Generation archetype parameters
[options="header" cols="1,12,30"]
|===
|Row|Parameter|Explanation
|1|archetypeGroupId|Group id of the archetype. should be *org.activiti*
|2|archetypeArtifactId|Artifact if of the archetype. should be *activiti-archetype-unittest*
|3|archetypeVersion|Activiti version used in the generated test project
|4|groupId|Group id of the generated test project
|5|artifactId|Artifact id of the generated test project
|===


The directory structure of the generated project would be like this:
----
.
├── pom.xml
└── src
    └── test
        ├── java
        │   └── org
        │       └── myGroup
        │           └── MyUnitTest.java
        └── resources
            ├── activiti.cfg.xml
            ├── log4j.properties
            └── org
                └── myGroup
                    └── my-process.bpmn20.xml
----

You can modify java unit test case and its corresponding process model, or add new test cases and process models.
If you are using the project to articulate a bug or a feature, test case should fail initially. It should then pass
after the desired bug is fixed or the desired feature is implemented.
Please make sure to clean the project by typing *mvn clean* before sending it.

[[docker]]

=== Docker images
[[dockerIntroduction]]

==== Introduction

https://www.docker.com/[Docker] is a fantastic virtualization tool. It allows you package an application with all of its dependencies into a
standardized unit for software development. People can build pretested images and put them in a shared hub. Other people can pull
the images and easily bring up and run the software.

Purpose of Activiti docker image is running the activiti explorer and the rest-api rapidly without dealing with gory details of setting up development environment.
It is specially beneficiary for the people who want to run, test and evaluate the Activiti as fast as possible.
It may also be valuable for demonstrations and presentations.

[[dockerSingleImage]]
==== Usage
The first step is to install docker if it is not already done. https://docs.docker.com/engine/installation/[Installation] is very easy and straight forward. Binary installation media is available for nearly every major OS.
After installation of Docker, the activiti image and its dependencies should be pulled into the local machine: This command will do the job:

[source]
docker pull activiti/activiti-single-image:latest explorer


It may take some time depending on the Internet connection speed for the images to be downloaded.
Pulling is required only the first time or when there is a new version of the image available on the hub.
The next step is to run the image and create the container:

[source]
docker run -p 8080:8080  -t -i activiti/activiti-single-image:latest explorer

That is it, the image is up, and explorer web application is running. You can access it in your browser using this URL:

[source]
localhost:8080/activiti-explorer

The port number on the local machine can be changed by modifying the second part of the 8080:8080 argument.

The last parameter, determines the application to run. There are two options possible:

* explorer
* rest

Selecting "rest" causes the rest-api to run. For example this Url will get back list of deployments:
[source]
http://kermit:kermit@localhost:8080/activiti-rest/service/repository/deployments

If no parameter is provided, the default would be "explorer".


[[dockerBuild]]
==== Build docker image
Docker is built using a Dockerfile located in tooling/dockerImage/singleImage directory. A utility batch file, named "buildImage.sh" contains the command line for building the image.
If the built image is going to be used by others, it should be pushed into the docker hub using a command like:
[source]
docker push activiti/activiti-single-image:latest



[[jmxQuickStart]]
