
== Operation Control

[[JMX]]


=== JMX

[[jmxIntroduction]]

==== Introduction


It is possible to connect to activiti engine using standard Java Management Extensions (JMX) technology in order to get information or to change its behavior. Any standard JMX client can be used for that purpose. Enabling and disabling Job Executor, deploy new process definition files and deleting them are just samples of what could be done using JMX without writing a single line of code.
      

[[jmxQuickStart]]


==== Quick Start

By default JMX is not enabled. To enable JMX in its default configuration, it is enough to add the activiti-jmx jar file to your classpath, using Maven or by any other means. In case you are using Maven, you can add proper dependency by adding the following lines in your pom.xml:

[source,xml,linenums]            
----
<dependency>
  <groupId>org.activiti</groupId>
  <artifactId>activiti-jmx</artifactId>
  <version>latest.version</version>
</dependency>                    
----

After adding the dependency and building process engine, JMX connection is ready to be used. Just run jconsole available in standard JDK distribution. In list of local processes, you will see JVM containing activiti. If for any reason the proper JVM is not listed in "local processes" section, try connecting to it using this URL in "Remote Process" section:
        

----
service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi/activiti        
----

You can find the your exact local URL in your log files. After connecting, you can see the standard JVM statistics and Mbeans. You can view Activiti specific MBeans by selecting Mbeans tab and select "org.activiti.jmx.Mbeans" on the right panel. By selecting any MBean, you can query information or change configuration. This snapshot shows how the jconsole looks like:
            
Any JMX client not limited to jconsole can be used to access Mbeans. Most of data center monitoring tools have some connectors which enables them to connect to JMX MBeans.
        

==== Attributes and operations


Here is a list available attributes and operations at this moment. This list may extend in future releases based on needs.

[options="header"]
|===============
|MBean|Type|Name|Description
|ProcessDefinitionsMBean|Attribute|processDefinitons|+Id+, +Name+, +Version+, +IsSuspended+ properties of deployed process definitions as a list of list of Strings
||Attribute|deployments|+Id+, +Name+, +TenantId+ properties of current deployments
||method|getProcessDefinitionById(String id)|+Id+, +Name+, +Version+ and +IsSuspended+ properties of the process definition with given id
||method|deleteDeployment(String id)|Deletes deployment with the given +Id+
||method|suspendProcessDefinitionById(String id)|Suspends the process definition with the given +Id+
||method|activatedProcessDefinitionById(String id)|Activates the process definition with the given +Id+
||method|suspendProcessDefinitionByKey(String id)|Suspends the process definition with the given +key+
||method|activatedProcessDefinitionByKey(String id)|Activates the process definition with the given +key+
||method|deployProcessDefinition(String resourceName, String processDefinitionFile)|Deploys the process definition file
|JobExecutorMBean|attribute|isJobExecutorActivated|Returns true if job executor is activated, false otherwise
||method|setJobExecutorActivate(Boolean active)|Activates and Deactivates Job executor based on the given boolean

|===============

     
==== Configuration

JMX uses default configuration to make it easy to deploy with the most used configuration. However it is easy to change the default configuration. You can do it programmatically or via configuration file. The following code excerpt shows  how this could be done in the configuration file:

[source,xml,linenums]        
----
<bean id="processEngineConfiguration" class="...SomeProcessEngineConfigurationClass">
  ...
  <property name="configurators">
    <list>
	  <bean class="org.activiti.management.jmx.JMXConfigurator">
              
	    <property name="connectorPort" value="1912" />
        <property name="serviceUrlPath" value="/jmxrmi/activiti" />

		...
      </bean>
    </list>
  </property>
</bean>                     
----

This table shows what parameters you can configure along with their default values:

[options="header"]
|===============
|Name|Default value|Description
|disabled|false|if set, JMX will not be started even in presence of the dependency
|domain|org.activiti.jmx.Mbeans|Domain of MBean
|createConnector|true|if true, creates a connector for the started MbeanServer
|MBeanDomain|DefaultDomain|domain of MBean server
|registryPort|1099|appears in the service URL as registry port
|serviceUrlPath|/jmxrmi/activiti|appears in the service URL
|connectorPort|-1|if greater than zero, will appear in service URL as connector port

|===============


     
==== JMX Service URL


The JMX service URL has the following format:

          
----
service:jmx:rmi://<hostName>:<connectorPort>/jndi/rmi://<hostName>:<registryPort>/<serviceUrlPath>          
----

+hostName+ will be automatically set to the network name of the machine.
+connectorPort+, +registryPort+ and +serviceUrlPath+ can be configured.
        

If +connectionPort+ is less than zero, the corresponding part of service URL will be dropped and it will be simplified to:
          
----
service:jmx:rmi:///jndi/rmi://:<hostname>:<registryPort>/<serviceUrlPath>          
----


       

