DROP TABLE IF EXISTS  ACT_GE_PROPERTY CASCADE;
DROP TABLE IF EXISTS  ACT_GE_BYTEARRAY CASCADE;
DROP TABLE IF EXISTS  ACT_RE_MODEL CASCADE;
DROP TABLE IF EXISTS  ACT_RE_DEPLOYMENT CASCADE;
DROP TABLE IF EXISTS  ACT_RE_PROCDEF CASCADE;
DROP TABLE IF EXISTS  ACT_RU_IDENTITYLINK CASCADE;
DROP TABLE IF EXISTS  ACT_RU_VARIABLE CASCADE;
DROP TABLE IF EXISTS  ACT_RU_TASK CASCADE;
DROP TABLE IF EXISTS  ACT_RU_EXECUTION CASCADE;
DROP TABLE IF EXISTS  ACT_RU_JOB CASCADE;
DROP TABLE IF EXISTS  ACT_RU_EVENT_SUBSCR CASCADE;

DROP TABLE IF EXISTS  ACT_HI_PROCINST CASCADE;
DROP TABLE IF EXISTS  ACT_HI_ACTINST CASCADE;
DROP TABLE IF EXISTS  ACT_HI_VARINST CASCADE;
DROP TABLE IF EXISTS  ACT_HI_TASKINST CASCADE;
DROP TABLE IF EXISTS  ACT_HI_DETAIL CASCADE;
DROP TABLE IF EXISTS  ACT_HI_COMMENT CASCADE;
DROP TABLE IF EXISTS  ACT_HI_ATTACHMENT CASCADE;

DROP TABLE IF EXISTS  ACT_ID_INFO CASCADE;
DROP TABLE IF EXISTS  ACT_ID_MEMBERSHIP CASCADE;
DROP TABLE IF EXISTS  ACT_ID_GROUP CASCADE;
DROP TABLE IF EXISTS  ACT_ID_USER CASCADE;
