if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_CONFIG') drop table ACT_CY_CONFIG;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_LINK') drop table ACT_CY_LINK;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_PEOPLE_LINK') drop table ACT_CY_PEOPLE_LINK;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_TAG') drop table ACT_CY_TAG;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_COMMENT') drop table ACT_CY_COMMENT;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_V_FOLDER') drop table ACT_CY_V_FOLDER;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_CY_PROCESS_SOLUTION') drop table ACT_CY_PROCESS_SOLUTION;