/* Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.activiti.cycle;

import org.activiti.cycle.impl.CycleServiceImpl;


/**
 * Superclass for the composite of folders and files. Holds a reference to the
 * API used to query sub folders and files in order to enable lazy loading of
 * them.
 * 
 * @author bernd.ruecker@camunda.com
 */
public interface RepositoryNode {

  /**
   * local part of the URL for node. This is the one and only used unique
   * identifier for the node used by the client and the repository API. All
   * details can be queried by this URL later on, by adding the repo base URL to
   * the beginning.
   * 
   * 
   * TODO: When thinking about Metadata-Persietnce, maybe introduce an UUID?
   * TODO: Maybe use BASE 64 Encoding for GUI, where do we put that?
   */

  /**
   * ID of the {@link RepositoryConnector} this {@link RepositoryNode}
   * originally "belongs" to.
   */
  public String getConnectorId();

  /**
   * <b>The current path is used in the {@link RepositoryConnector}-API, so if
   * you don't have a special use case use that, not this one!</b>
   * 
   * Unique ID of the {@link RepositoryNode} within the original
   * {@link RepositoryConnector} identified by the connectorId.
   * 
   * For Signavio the ID is simply an UUID generated by Signavio. For FileSystem
   * this is the "local" part of the absolute path of the file WITHOUT the
   * configured root folder of the FileSystem connector. For other repos this
   * may be whatever it needs to be, the client shouldn't really care.
   */
  public String getOriginalNodeId();

  /**
   * <b>The current path is used in the {@link RepositoryConnector}-API, so if
   * you don't have a special use case use that, not this one!</b>
   * 
   * ID composed of the connectorId and the node id, which results in a Cycle
   * wide unique ID for an {@link RepositoryNode}
   */
  public String getGlobalUniqueId();

  /**
   * <b>The current path is used in the {@link RepositoryConnector}-API, so if
   * you don't have a special use case use this one!</b>
   * 
   * current path of artifact in the current "context", so for example the id of
   * the artifact when using the {@link CycleServiceImpl} or maybe another
   * accumulating connector like tags, ... This ID is <b>NOT</b> globally unique
   * and just always used in one special context. It may even be changed by
   * connectors like the {@link CycleServiceImpl} on the fly.
   */
  public String getCurrentPath(); 

  public RepositoryNodeMetadata getMetadata();
}
