name: Check Ext build
description: Checks if the build is a dependabot build or external contribution

inputs:
  gh-token:
    description: 'GitHub token'
    required: true

outputs:
  skip-build:
    description: "Skip the build"
    value: ${{ steps.check_build.outputs.SKIP_BUILD }}

permissions:
  contents: read
  actions: read
  checks: write

runs:
  using: composite
  steps:
    - name: Check build
      id: check_build
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        SENDER_LOGIN: ${{ github.event.sender.login }}
        EVENT_ACTION: ${{ github.event.action }}
        LABEL: ${{ github.event.label.name }}
        PR_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
        REPO_NAME: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
      shell: bash
      run: |
        GH_ACTION_LABEL=$(gh api /repos/$GITHUB_REPOSITORY/issues/$GITHUB_PR_NUMBER/labels --jq '.[].name')
        echo "Found labels $GH_ACTION_LABEL"

