name: Check Ext build
description: Checks if the build is a dependabot build or external contribution

runs:
  using: composite
  steps:

    - name: Check build
      env:
        SENDER_LOGIN: ${{ github.event.sender.login }}
        EVENT_NAME: ${{ github.event_name }}
        LABEL: ${{ github.event.label.name }}
      shell: bash
      run: |
        if [ $SENDER_LOGIN != 'dependabot[bot]' ]; then
          exit 0
        fi

        if [[ $EVENT_NAME == 'labeled' && $LABEL == 'CI' ]]
        then
          echo "Dependabot build will run with actor who labeled the PR"
        else
          echo "This workflow run was triggered by dependabot. Validate the upgraded dependencies, then add the 'CI' label to the pull request to trigger this workflow."
          exit 1
        fi
