name: Check Ext build
description: Checks if the build is a dependabot build or external contribution

inputs:
  gh-token:
    description: 'GitHub token'
    required: true

outputs:
  skip-build:
    description: "Skip the build"
    value: ${{ steps.check_build.outputs.SKIP_BUILD }}

permissions:
  contents: read
  actions: read
  checks: write

runs:
  using: composite
  steps:
    - name: Check build
      id: check_build
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        SENDER_LOGIN: ${{ github.event.sender.login }}
        EVENT_ACTION: ${{ github.event.action }}
        LABEL: ${{ github.event.label.name }}
        PR_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
        REPO_NAME: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
      shell: bash
      run: |
        LABELS=$(gh api /repos/$GITHUB_REPOSITORY/issues/$GITHUB_PR_NUMBER/labels --jq '.[].name')
        echo "Found labels $LABELS"
        echo "GITHUB_ACTOR $GITHUB_ACTOR"

        if [[ $SENDER_LOGIN != 'dependabot[bot]' && (-z $PR_REPO_NAME || $PR_REPO_NAME == $REPO_NAME) ]]
        then
          exit 0
        fi

        if [[ $EVENT_ACTION == 'labeled' && $LABEL == "CI" ]]
        then
          echo "This workflow will run with actor who labeled the PR"
          if [ "$GITHUB_ACTOR" == "mauriziovitale" ] && [ "$LABELS" == *"gh_action"* ]
            echo "PR opened by dependabot and with gh_action we can skip the build"
            echo "SKIP_BUILD=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "This workflow run was triggered by dependabot or an external contributor. Check and validate the changes, then add the 'CI' label to the pull request to trigger this workflow."
          exit 1
        fi

