package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "act_hi_comment")
public class Comment implements java.io.Serializable {

    private String id;
    private String type;
    private Date time;
    private String userId;
    private String taskId;
    private String procInstId;
    private String action;
    private String message;
    private byte[] fullMsg;

    public Comment() {
    }

    public Comment(String id, Date time) {
        this.id = id;
        this.time = time;
    }

    public Comment(String id, String type, Date time, String userId, String taskId, String procInstId, String action, String message, byte[] fullMsg) {
        this.id = id;
        this.type = type;
        this.time = time;
        this.userId = userId;
        this.taskId = taskId;
        this.procInstId = procInstId;
        this.action = action;
        this.message = message;
        this.fullMsg = fullMsg;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "type_")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time_", nullable = false, length = 29)
    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    @Column(name = "user_id_")
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "task_id_", length = 64)
    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Column(name = "proc_inst_id_", length = 64)
    public String getProcInstId() {
        return this.procInstId;
    }

    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }

    @Column(name = "action_")
    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    @Column(name = "message_", length = 4000)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name = "full_msg_")
    public byte[] getFullMsg() {
        return this.fullMsg;
    }

    public void setFullMsg(byte[] fullMsg) {
        this.fullMsg = fullMsg;
    }
}


