package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * EventLogEntry generated by hbm2java
 */
@Entity
@Table(name = "act_evt_log")
public class EventLogEntry implements java.io.Serializable {

    private int logNr;
    private String type;
    private String procDefId;
    private String procInstId;
    private String executionId;
    private String taskId;
    private Date timeStamp;
    private String userId;
    private byte[] data;
    private String lockOwner;
    private Date lockTime;
    private Short isProcessed;

    public EventLogEntry() {
    }

    public EventLogEntry(int logNr, Date timeStamp) {
        this.logNr = logNr;
        this.timeStamp = timeStamp;
    }

    public EventLogEntry(int logNr, String type, String procDefId, String procInstId, String executionId, String taskId, Date timeStamp, String userId, byte[] data, String lockOwner, Date lockTime, Short isProcessed) {
        this.logNr = logNr;
        this.type = type;
        this.procDefId = procDefId;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.taskId = taskId;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.data = data;
        this.lockOwner = lockOwner;
        this.lockTime = lockTime;
        this.isProcessed = isProcessed;
    }

    @Id
    @Column(name = "log_nr_", unique = true, nullable = false)
    public int getLogNr() {
        return this.logNr;
    }

    public void setLogNr(int logNr) {
        this.logNr = logNr;
    }

    @Column(name = "type_", length = 64)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "proc_def_id_", length = 64)
    public String getProcDefId() {
        return this.procDefId;
    }

    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }

    @Column(name = "proc_inst_id_", length = 64)
    public String getProcInstId() {
        return this.procInstId;
    }

    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }

    @Column(name = "execution_id_", length = 64)
    public String getExecutionId() {
        return this.executionId;
    }

    public void setExecutionId(String executionId) {
        this.executionId = executionId;
    }

    @Column(name = "task_id_", length = 64)
    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time_stamp_", nullable = false, length = 29)
    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Column(name = "user_id_")
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "data_")
    public byte[] getData() {
        return this.data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    @Column(name = "lock_owner_")
    public String getLockOwner() {
        return this.lockOwner;
    }

    public void setLockOwner(String lockOwner) {
        this.lockOwner = lockOwner;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lock_time_", length = 29)
    public Date getLockTime() {
        return this.lockTime;
    }

    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    @Column(name = "is_processed_")
    public Short getIsProcessed() {
        return this.isProcessed;
    }

    public void setIsProcessed(Short isProcessed) {
        this.isProcessed = isProcessed;
    }
}


