package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * EventSubscription generated by hbm2java
 */
@Entity
@Table(name = "act_ru_event_subscr")
public class EventSubscription implements java.io.Serializable {

    private String id;
    private Execution execution;
    private Integer rev;
    private String eventType;
    private String eventName;
    private String procInstId;
    private String activityId;
    private String configuration;
    private Date created;
    private String procDefId;
    private String tenantId;

    public EventSubscription() {
    }

    public EventSubscription(String id, String eventType, Date created) {
        this.id = id;
        this.eventType = eventType;
        this.created = created;
    }

    public EventSubscription(String id, Execution execution, Integer rev, String eventType, String eventName, String procInstId, String activityId, String configuration, Date created, String procDefId, String tenantId) {
        this.id = id;
        this.execution = execution;
        this.rev = rev;
        this.eventType = eventType;
        this.eventName = eventName;
        this.procInstId = procInstId;
        this.activityId = activityId;
        this.configuration = configuration;
        this.created = created;
        this.procDefId = procDefId;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "execution_id_")
    public Execution getExecution() {
        return this.execution;
    }

    public void setExecution(Execution execution) {
        this.execution = execution;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "event_type_", nullable = false)
    public String getEventType() {
        return this.eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    @Column(name = "event_name_")
    public String getEventName() {
        return this.eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    @Column(name = "proc_inst_id_", length = 64)
    public String getProcInstId() {
        return this.procInstId;
    }

    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }

    @Column(name = "activity_id_", length = 64)
    public String getActivityId() {
        return this.activityId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    @Column(name = "configuration_")
    public String getConfiguration() {
        return this.configuration;
    }

    public void setConfiguration(String configuration) {
        this.configuration = configuration;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_", nullable = false, length = 29)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "proc_def_id_", length = 64)
    public String getProcDefId() {
        return this.procDefId;
    }

    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }

    @Column(name = "tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}


