package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * HistoricActivityInstance generated by hbm2java
 */
@Entity
@Table(name = "act_hi_actinst")
public class HistoricActivityInstance implements java.io.Serializable {

    private String id;
    private String procDefId;
    private String procInstId;
    private String executionId;
    private String actId;
    private String taskId;
    private String callProcInstId;
    private String actName;
    private String actType;
    private String assignee;
    private Date startTime;
    private Date endTime;
    private Long duration;
    private String tenantId;

    public HistoricActivityInstance() {
    }

    public HistoricActivityInstance(String id, String procDefId, String procInstId, String executionId, String actId, String actType, Date startTime) {
        this.id = id;
        this.procDefId = procDefId;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.actId = actId;
        this.actType = actType;
        this.startTime = startTime;
    }

    public HistoricActivityInstance(String id, String procDefId, String procInstId, String executionId, String actId, String taskId, String callProcInstId, String actName, String actType, String assignee, Date startTime, Date endTime, Long duration, String tenantId) {
        this.id = id;
        this.procDefId = procDefId;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.actId = actId;
        this.taskId = taskId;
        this.callProcInstId = callProcInstId;
        this.actName = actName;
        this.actType = actType;
        this.assignee = assignee;
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "proc_def_id_", nullable = false, length = 64)
    public String getProcDefId() {
        return this.procDefId;
    }

    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }

    @Column(name = "proc_inst_id_", nullable = false, length = 64)
    public String getProcInstId() {
        return this.procInstId;
    }

    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }

    @Column(name = "execution_id_", nullable = false, length = 64)
    public String getExecutionId() {
        return this.executionId;
    }

    public void setExecutionId(String executionId) {
        this.executionId = executionId;
    }

    @Column(name = "act_id_", nullable = false)
    public String getActId() {
        return this.actId;
    }

    public void setActId(String actId) {
        this.actId = actId;
    }

    @Column(name = "task_id_", length = 64)
    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Column(name = "call_proc_inst_id_", length = 64)
    public String getCallProcInstId() {
        return this.callProcInstId;
    }

    public void setCallProcInstId(String callProcInstId) {
        this.callProcInstId = callProcInstId;
    }

    @Column(name = "act_name_")
    public String getActName() {
        return this.actName;
    }

    public void setActName(String actName) {
        this.actName = actName;
    }

    @Column(name = "act_type_", nullable = false)
    public String getActType() {
        return this.actType;
    }

    public void setActType(String actType) {
        this.actType = actType;
    }

    @Column(name = "assignee_")
    public String getAssignee() {
        return this.assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time_", nullable = false, length = 29)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time_", length = 29)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Column(name = "duration_")
    public Long getDuration() {
        return this.duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    @Column(name = "tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}


