package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdentityInfo generated by hbm2java
 */
@Entity
@Table(name = "act_id_info")
public class IdentityInfo implements java.io.Serializable {

    private String id;
    private Integer rev;
    private String userId;
    private String type;
    private String key;
    private String value;
    private byte[] password;
    private String parentId;

    public IdentityInfo() {
    }

    public IdentityInfo(String id) {
        this.id = id;
    }

    public IdentityInfo(String id, Integer rev, String userId, String type, String key, String value, byte[] password, String parentId) {
        this.id = id;
        this.rev = rev;
        this.userId = userId;
        this.type = type;
        this.key = key;
        this.value = value;
        this.password = password;
        this.parentId = parentId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "user_id_", length = 64)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "type_", length = 64)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "key_")
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @Column(name = "value_")
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "password_")
    public byte[] getPassword() {
        return this.password;
    }

    public void setPassword(byte[] password) {
        this.password = password;
    }

    @Column(name = "parent_id_")
    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
}


