package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * IdentityLink generated by hbm2java
 */
@Entity
@Table(name = "act_ru_identitylink")
public class IdentityLink implements java.io.Serializable {

    private String id;
    private ProcessDefinition processDefinition;
    private Task task;
    private Execution execution;
    private Integer rev;
    private String groupId;
    private String type;
    private String userId;

    public IdentityLink() {
    }

    public IdentityLink(String id) {
        this.id = id;
    }

    public IdentityLink(String id, ProcessDefinition processDefinition, Task task, Execution execution, Integer rev, String groupId, String type, String userId) {
        this.id = id;
        this.processDefinition = processDefinition;
        this.task = task;
        this.execution = execution;
        this.rev = rev;
        this.groupId = groupId;
        this.type = type;
        this.userId = userId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_def_id_")
    public ProcessDefinition getProcessDefinition() {
        return this.processDefinition;
    }

    public void setProcessDefinition(ProcessDefinition processDefinition) {
        this.processDefinition = processDefinition;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id_")
    public Task getTask() {
        return this.task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_inst_id_")
    public Execution getExecution() {
        return this.execution;
    }

    public void setExecution(Execution execution) {
        this.execution = execution;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "group_id_")
    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @Column(name = "type_")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "user_id_")
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}


