package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "act_ru_job")
public class Job implements java.io.Serializable {

    private String id;
    private ByteArray byteArray;
    private Integer rev;
    private String type;
    private Date lockExpTime;
    private String lockOwner;
    private Boolean exclusive;
    private String executionId;
    private String processInstanceId;
    private String procDefId;
    private Integer retries;
    private String exceptionMsg;
    private Date duedate;
    private String repeat;
    private String handlerType;
    private String handlerCfg;
    private String tenantId;

    public Job() {
    }

    public Job(String id, String type) {
        this.id = id;
        this.type = type;
    }

    public Job(String id, ByteArray byteArray, Integer rev, String type, Date lockExpTime, String lockOwner, Boolean exclusive, String executionId, String processInstanceId, String procDefId, Integer retries, String exceptionMsg, Date duedate, String repeat, String handlerType, String handlerCfg, String tenantId) {
        this.id = id;
        this.byteArray = byteArray;
        this.rev = rev;
        this.type = type;
        this.lockExpTime = lockExpTime;
        this.lockOwner = lockOwner;
        this.exclusive = exclusive;
        this.executionId = executionId;
        this.processInstanceId = processInstanceId;
        this.procDefId = procDefId;
        this.retries = retries;
        this.exceptionMsg = exceptionMsg;
        this.duedate = duedate;
        this.repeat = repeat;
        this.handlerType = handlerType;
        this.handlerCfg = handlerCfg;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exception_stack_id_")
    public ByteArray getByteArray() {
        return this.byteArray;
    }

    public void setByteArray(ByteArray byteArray) {
        this.byteArray = byteArray;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "type_", nullable = false)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lock_exp_time_", length = 29)
    public Date getLockExpTime() {
        return this.lockExpTime;
    }

    public void setLockExpTime(Date lockExpTime) {
        this.lockExpTime = lockExpTime;
    }

    @Column(name = "lock_owner_")
    public String getLockOwner() {
        return this.lockOwner;
    }

    public void setLockOwner(String lockOwner) {
        this.lockOwner = lockOwner;
    }

    @Column(name = "exclusive_")
    public Boolean getExclusive() {
        return this.exclusive;
    }

    public void setExclusive(Boolean exclusive) {
        this.exclusive = exclusive;
    }

    @Column(name = "execution_id_", length = 64)
    public String getExecutionId() {
        return this.executionId;
    }

    public void setExecutionId(String executionId) {
        this.executionId = executionId;
    }

    @Column(name = "process_instance_id_", length = 64)
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    @Column(name = "proc_def_id_", length = 64)
    public String getProcDefId() {
        return this.procDefId;
    }

    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }

    @Column(name = "retries_")
    public Integer getRetries() {
        return this.retries;
    }

    public void setRetries(Integer retries) {
        this.retries = retries;
    }

    @Column(name = "exception_msg_", length = 4000)
    public String getExceptionMsg() {
        return this.exceptionMsg;
    }

    public void setExceptionMsg(String exceptionMsg) {
        this.exceptionMsg = exceptionMsg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "duedate_", length = 29)
    public Date getDuedate() {
        return this.duedate;
    }

    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    @Column(name = "repeat_")
    public String getRepeat() {
        return this.repeat;
    }

    public void setRepeat(String repeat) {
        this.repeat = repeat;
    }

    @Column(name = "handler_type_")
    public String getHandlerType() {
        return this.handlerType;
    }

    public void setHandlerType(String handlerType) {
        this.handlerType = handlerType;
    }

    @Column(name = "handler_cfg_", length = 4000)
    public String getHandlerCfg() {
        return this.handlerCfg;
    }

    public void setHandlerCfg(String handlerCfg) {
        this.handlerCfg = handlerCfg;
    }

    @Column(name = "tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}


