package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name = "act_re_model")
public class Model implements java.io.Serializable {

    private String id;
    private ByteArray byteArrayByEditorSourceValueId;
    private Deployment deployment;
    private ByteArray byteArrayByEditorSourceExtraValueId;
    private Integer rev;
    private String name;
    private String key;
    private String category;
    private Date createTime;
    private Date lastUpdateTime;
    private Integer version;
    private String metaInfo;
    private String tenantId;

    public Model() {
    }

    public Model(String id) {
        this.id = id;
    }

    public Model(String id, ByteArray byteArrayByEditorSourceValueId, Deployment deployment, ByteArray byteArrayByEditorSourceExtraValueId, Integer rev, String name, String key, String category, Date createTime, Date lastUpdateTime, Integer version, String metaInfo, String tenantId) {
        this.id = id;
        this.byteArrayByEditorSourceValueId = byteArrayByEditorSourceValueId;
        this.deployment = deployment;
        this.byteArrayByEditorSourceExtraValueId = byteArrayByEditorSourceExtraValueId;
        this.rev = rev;
        this.name = name;
        this.key = key;
        this.category = category;
        this.createTime = createTime;
        this.lastUpdateTime = lastUpdateTime;
        this.version = version;
        this.metaInfo = metaInfo;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "editor_source_value_id_")
    public ByteArray getByteArrayByEditorSourceValueId() {
        return this.byteArrayByEditorSourceValueId;
    }

    public void setByteArrayByEditorSourceValueId(ByteArray byteArrayByEditorSourceValueId) {
        this.byteArrayByEditorSourceValueId = byteArrayByEditorSourceValueId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deployment_id_")
    public Deployment getDeployment() {
        return this.deployment;
    }

    public void setDeployment(Deployment deployment) {
        this.deployment = deployment;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "editor_source_extra_value_id_")
    public ByteArray getByteArrayByEditorSourceExtraValueId() {
        return this.byteArrayByEditorSourceExtraValueId;
    }

    public void setByteArrayByEditorSourceExtraValueId(ByteArray byteArrayByEditorSourceExtraValueId) {
        this.byteArrayByEditorSourceExtraValueId = byteArrayByEditorSourceExtraValueId;
    }

    @Column(name = "rev_")
    public Integer getRev() {
        return this.rev;
    }

    public void setRev(Integer rev) {
        this.rev = rev;
    }

    @Column(name = "name_")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "key_")
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @Column(name = "category_")
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time_", length = 29)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_time_", length = 29)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Column(name = "version_")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "meta_info_", length = 4000)
    public String getMetaInfo() {
        return this.metaInfo;
    }

    public void setMetaInfo(String metaInfo) {
        this.metaInfo = metaInfo;
    }

    @Column(name = "tenant_id_")
    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}


