name: Create Pre-release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"

jobs:
  create-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Create prerelease
        env:
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh release create $TAG --prerelease -t $TAG
