name: Dependabot auto-merge
on:
  pull_request:
    branches:
      - develop

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/automate-dependabot@v1.40.1
      with:
        token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
