name: Stale PR Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write

jobs:
  stale-pr-cleanup:
    uses: Alfresco/alfresco-build-tools/.github/workflows/stale-pr-cleanup.yml@1d671f8f10336861c89c67be57c6648d98876103 # v18.19.0
